'use client';import{useState}from'react';
const menu={Закуски:[['Печёный порей','фундук, крем из фермерской сметаны','640 ₽'],['Крудо из сибаса','зелёная клубника, укропное масло','890 ₽'],['Тёплый хлеб','взбитое сливочное масло','320 ₽']],Салаты:[['Сезонные томаты','страчателла, базилик','780 ₽'],['Зелёный салат','яблоко, фенхель, травы','590 ₽']],Горячее:[['Форель на огне','щавель, копчёный картофель','1 290 ₽'],['Утиная грудка','вишня, перечный соус','1 480 ₽'],['Стейк из капусты','мисо, семечки','780 ₽']],Десерты:[['Павлова','ревень, вербена','590 ₽'],['Шоколадный тарт','оливковое масло, морская соль','620 ₽']],Напитки:[['Петнат','бокал / бутылка','650 / 3 200 ₽'],['Сезонный кордиал','груша, можжевельник','390 ₽']]} as const;
export default function Home(){const[cat,setCat]=useState<keyof typeof menu>('Закуски');const[open,setOpen]=useState(false);const[done,setDone]=useState(false);return <main><nav><a className="brand" href="#top">SERA<span>●</span></a><div><a href="#about">О ресторане</a><a href="#menu">Меню</a><a href="#visit">Контакты</a><button onClick={()=>{setDone(false);setOpen(true)}}>Забронировать стол</button></div></nav>
<header id="top"><img src="https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1800&q=85" alt="Сезонные блюда на столе ресторана"/><div className="heroText"><p className="eyebrow">Сезонное меню · Живой огонь</p><h1>Вкус следует<br/><em>за сезоном.</em></h1><p>Локальные продукты и вечера, к которым хочется возвращаться.</p><div><a href="#menu">Посмотреть меню ↓</a><button onClick={()=>setOpen(true)}>Забронировать</button></div></div><aside>Санкт-Петербург<br/>59.9343° N</aside></header>
<section id="about" className="intro"><p>О РЕСТОРАНЕ</p><h2>Знакомые продукты.<br/>Новый взгляд.</h2><p className="copy">SERA — вымышленный ресторан современной северной кухни. Меню меняется вместе с сезоном, а в центре каждого блюда — понятный продукт и живой огонь.</p></section>
<section className="plates"><article><img src="https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1000&q=85" alt="Овощное блюдо"/><span>ОВОЩИ</span><h3>Сад и сезон</h3></article><article><img src="https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=85" alt="Блюдо на огне"/><span>ТЕХНИКА</span><h3>Живой огонь</h3></article><article><img src="https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1000&q=85" alt="Интерьер ресторана"/><span>АТМОСФЕРА</span><h3>Останьтесь дольше</h3></article></section>
<section id="menu" className="menu"><div><p className="eyebrow">À LA CARTE · ЦЕНЫ ДЛЯ ПРИМЕРА</p><h2>Меню</h2></div><div className="tabs" role="tablist">{Object.keys(menu).map(x=><button role="tab" aria-selected={cat===x} onClick={()=>setCat(x as keyof typeof menu)} key={x}>{x}</button>)}</div><div className="items">{menu[cat].map(([n,d,p])=><article key={n}><div><h3>{n}</h3><p>{d}</p></div><strong>{p}</strong></article>)}</div></section>
<section className="atmos"><img src="https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1800&q=85" alt="Блюда для общей подачи"/><blockquote>«Приходите на ужин.<br/>Останьтесь ради атмосферы».</blockquote></section>
<section className="chef"><div><p className="eyebrow">ШЕФ И ПОДХОД</p><h2>Продукт говорит<br/>первым.</h2><p>Кухня строится на уважении к сезону: минимум лишнего, точная техника и вкус, который не нужно объяснять.</p></div><img src="https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=1000&q=85" alt="Шеф на кухне"/></section>
<section id="visit" className="visit"><div><p className="eyebrow">АДРЕС И ЧАСЫ</p><h2>Большая Морская, 24<br/><small>вымышленный адрес</small></h2></div><div><h3>Время работы</h3><p>Пн–Чт 12:00–23:00<br/>Пт–Сб 12:00–00:00<br/>Вс 12:00–22:00</p></div><div><h3>Контакты</h3><p>+7 (000) 000-00-00<br/>hello@sera.demo</p></div></section>
<div className="map" aria-label="Схема расположения ресторана"><span>59.9343° N / 30.3351° E</span><b>SERA</b><i>Условная схема · Вымышленный адрес</i></div><section className="reserve"><p>Проведите вечер с нами.</p><h2>Ваш стол ждёт.</h2><button onClick={()=>setOpen(true)}>Забронировать стол</button></section>
<footer><a className="brand" href="#top">SERA<span>●</span></a><p>Демонстрационный проект для портфолио · Max Volkov · 2026</p><a href="#top">Наверх ↑</a></footer>
{open&&<div className="modal" role="dialog" aria-modal="true" aria-label="Демонстрационное бронирование"><form onSubmit={e=>{e.preventDefault();setDone(true)}}><button type="button" className="close" onClick={()=>setOpen(false)}>×</button>{done?<div className="success"><b>✓</b><h2>Заявка принята</h2><p>Это демонстрационное состояние. Данные никуда не отправлены.</p><button type="button" onClick={()=>setOpen(false)}>Закрыть</button></div>:<><p className="eyebrow">БРОНИРОВАНИЕ</p><h2>Забронировать стол</h2><label>Имя<input required placeholder="Ваше имя"/></label><label>Дата<input required type="date"/></label><label>Гости<select><option>2 гостя</option><option>3 гостя</option><option>4 гостя</option></select></label><button>Отправить заявку</button><small>Демонстрационная форма: данные не передаются и не сохраняются.</small></>}</form></div>}</main>}
