'use client';
import {useState} from 'react';
const menu={Small:[['Burnt leek','hazelnut, cultured cream','₽ 640'],['Sea bass crudo','green strawberry, dill','₽ 890'],['Warm bread','whipped brown butter','₽ 320']],Fire:[['Trout','sorrel, smoked potato','₽ 1 290'],['Duck breast','cherry, pepper jus','₽ 1 480'],['Cabbage steak','miso, sunflower seed','₽ 780']],Pasta:[['Agnolotti','goat cheese, lemon','₽ 920'],['Tagliolini','crab, bisque, chilli','₽ 1 390']],Sweet:[['Pavlova','rhubarb, verbena','₽ 590'],['Chocolate tart','olive oil, sea salt','₽ 620']],Drinks:[['Pet-nat','glass / bottle','₽ 650 / 3 200'],['Seasonal cordial','pear, juniper','₽ 390']]} as const;
export default function Home(){const [cat,setCat]=useState<keyof typeof menu>('Small');const [open,setOpen]=useState(false);return <main>
<nav><a className="brand" href="#top">SERA<span>●</span></a><div><a href="#menu">Menu</a><a href="#visit">Visit</a><button onClick={()=>setOpen(true)}>Book a table</button></div></nav>
<header id="top"><img src="https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1800&q=85" alt="Seasonal plates on a restaurant table"/><div className="heroText"><p className="eyebrow">Modern kitchen · DEMO CONCEPT</p><h1>Food that follows<br/><em>the season.</em></h1><p>Open fire, local produce and a room made for slow evenings.</p><a href="#menu">Explore the menu ↓</a></div><aside>Saint Petersburg<br/>59.9343° N</aside></header>
<section className="intro"><p>01 / Our table</p><h2>Familiar ingredients,<br/>seen a little differently.</h2><p className="copy">SERA is a fictional neighbourhood restaurant shaped by northern produce and live fire. The menu changes with what is best today.</p></section>
<section className="plates"><article><img src="https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1000&q=85" alt="Vegetable dish"/><span>01</span><h3>Garden first</h3></article><article><img src="https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=85" alt="Dish cooked over fire"/><span>02</span><h3>Open fire</h3></article><article><img src="https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1000&q=85" alt="Restaurant interior"/><span>03</span><h3>Stay awhile</h3></article></section>
<section id="menu" className="menu"><div><p className="eyebrow">02 / À la carte · DEMO PRICES</p><h2>The menu</h2></div><div className="tabs" role="tablist">{Object.keys(menu).map(x=><button role="tab" aria-selected={cat===x} onClick={()=>setCat(x as keyof typeof menu)} key={x}>{x}</button>)}</div><div className="items">{menu[cat].map(([n,d,p])=><article key={n}><div><h3>{n}</h3><p>{d}</p></div><strong>{p}</strong></article>)}</div></section>
<section className="atmos"><img src="https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1800&q=85" alt="Colourful shared plates"/><blockquote>“Come for dinner.<br/>Stay for the room.”</blockquote></section>
<section id="visit" className="visit"><div><p className="eyebrow">03 / Visit</p><h2>Bolshaya Morskaya, 24<br/><small>fictional address</small></h2></div><div><h3>Hours</h3><p>Mon–Thu 12:00–23:00<br/>Fri–Sat 12:00–00:00<br/>Sun 12:00–22:00</p></div><div><h3>Contact</h3><p>+7 (000) 000-00-00<br/>hello@sera.demo</p></div></section>
<div className="map" aria-label="Map placeholder"><span>59.9343° N / 30.3351° E</span><b>SERA</b><i>Map placeholder · Demo location</i></div>
<section className="reserve"><p>Make an evening of it.</p><h2>Your table is waiting.</h2><button onClick={()=>setOpen(true)}>Book a table</button></section>
<footer><a className="brand" href="#top">SERA<span>●</span></a><p>Demo concept · Created by Max Volkov · 2026</p><a href="#top">Back to top ↑</a></footer>
{open&&<div className="modal" role="dialog" aria-modal="true" aria-label="Demo reservation"><form onSubmit={e=>{e.preventDefault();setOpen(false);setTimeout(()=>alert('Demo booking received — no data was sent.'),50)}}><button type="button" className="close" onClick={()=>setOpen(false)}>×</button><p className="eyebrow">Demo reservation</p><h2>Book a table</h2><label>Name<input required placeholder="Your name"/></label><label>Date<input required type="date"/></label><label>Guests<select><option>2 guests</option><option>3 guests</option><option>4 guests</option></select></label><button>Request a table</button><small>Demo only. Your details are not transmitted or stored.</small></form></div>}</main>}
